### ISSUE TITLE
Chatting module tests

### ISSUE THREAD

**Issue by astro-angelfish** [osu-atri/osu-al1s#2]
I've completed the chatting module but have not tested them yet.

We might need to test them first to ensure everything works before we move on.

Doing this is extremely inconvenient for me because of the requirement of Windows attendance while this project is developed under Linux.

If there is any failures that you are unable to fix, you could just simply comment here and I'll handle it when I'm back.

**Comment by CloneWith** [comment]
lia fish

**Comment by astro-angelfish** [comment]
Closed by https://github.com/osu-atri/osu-al1s/commit/51713d94ff2e366a3351fbd57a689b89bac9dd6a
